
METEOSAT_SEVIRI :
  type : obs
  stream_id : 2
  # filenames : ['observations-od-ai-0001-201311-202505-msg-combined-seviri-o256-v1.zarr']
  filenames : ['observations-file-2014-2024-seviri-h512-v5.zarr']
  loss_weight : 1.0
  token_size : 128
  tokenize_spacetime : True
  max_num_targets: 65536
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords : 
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head : 
    ens_size : 1
    num_layers : 1


GOES_ABI :
  type : obs
  stream_id : 3
  # filenames : ['observations-file-2017-2024-abi-goes16-IR-o256-v2.zarr']
  filenames : ['observations-file-2017-2024-abi-goes16-IR-h512-v2.zarr']
  loss_weight : 1.0
  token_size : 128
  tokenize_spacetime : True
  max_num_targets: 65536
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords : 
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head : 
    ens_size : 1
    num_layers : 1


HIMAWARI_AHI :
  type : obs
  stream_id : 4
  # filenames : ['observations-file-2015-2022-himawari8-IR-o256-v1.zarr']
  filenames : ['observations-file-2015-2022-himawari8-IR-h512-v1.zarr']
  loss_weight : 1.0
  token_size : 128
  tokenize_spacetime : True
  max_num_targets: 65536
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords : 
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head : 
    ens_size : 1
    num_layers : 1
